name: currency_formatter_tools_example
description: A demonstration of the currency_formatter_tools package.

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  currency_formatter_tools:
    path: ../
